// Generated by LiveScript 1.2.0
$(window).load(function(){
  var lineWidth, overlayHeight, h1_height, timeline;
  window.app = new RealestateStreetView();
  lineWidth = $('h1 .line').width();
  overlayHeight = $('#overlay').height();
  TimelineMax.prototype.orangeLine = function(el, delay, stagger){
    var width;
    if (stagger == null) {
      stagger = 'line_width_stagger';
    }
    width = $(el).width() + _line_margin;
    this.to($('h1 .line'), 0.5, {
      marginLeft: 0,
      delay: delay,
      width: width
    }, stagger);
    return this.to($('h1'), 0.5, {
      delay: delay,
      width: width
    }, stagger);
  };
  TimelineMax.prototype.crossFade = function(_from, _to, stagger){
    this.to($(_from), 0.5, {
      opacity: 0,
      delay: 3
    }, stagger);
    return this.to($(_to), 0.5, {
      opacity: 1,
      delay: 3
    }, stagger);
  };
  $('h1 .text, h2 .text').each(function(){
    $(this).height($(this).height());
    return $(this).width($(this).width());
  });
  h1_height = $('h1 .text').outerHeight();
  $('h1').height(h1_height);
  $('h2').height($('h2 .text').outerHeight());
  $('h2 .text').css({
    marginTop: $('h2 .text').outerHeight() * -1
  });
  timeline = new TimelineMax({
    repeat: -1
  });
  return timeline.orangeLine('h1 .text1', 0).fromTo($('h1 .text1'), 0.5, {
    opacity: 1,
    marginBottom: -h1_height
  }, {
    marginBottom: 0
  }, 'text1in').orangeLine('h1 .text2', 3, 'text1out').crossFade('h1 .text1', 'h1 .text2', 'text1out').orangeLine('h1 .text3', 3, 'text2out').crossFade('h1 .text2', 'h1 .text3', 'text2out').to($('#overlay'), 0.5, {
    height: overlayHeight + $('h2 .text').outerHeight()
  }, 'text3').to($('h2 .text'), 0.5, {
    marginTop: 0
  }, 'text3').to($('h2 .text'), 0.5, {
    marginTop: $('h2 .text').outerHeight() * -1,
    delay: 5
  }, 'text3out').to($('#overlay'), 0.5, {
    height: overlayHeight,
    delay: 5
  }, 'text3out').to($('h1 .text3'), 0.5, {
    marginBottom: $('h1 .text3').outerHeight() * -1,
    delay: 5
  }, 'text3out').to($('h1 .line'), 0.5, {
    marginLeft: -lineWidth
  });
});